{{/*
[Task]: T030-T039
[From]: specs/004-phase-iv-kubernetes/tasks.md §Phase 5
[Description]: PodDisruptionBudget for high availability
*/}}
{{- if .Values.podDisruptionBudget.enabled }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "todo.fullname" . }}-frontend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "todo.frontend.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "todo.frontend.selectorLabels" . | nindent 6 }}

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "todo.fullname" . }}-backend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "todo.backend.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "todo.backend.selectorLabels" . | nindent 6 }}
{{- end }}
