{{/*
[Task]: T030-T039
[From]: specs/004-phase-iv-kubernetes/tasks.md §Phase 5
[Description]: ServiceAccount for pod identity
*/}}
{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "todo.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "todo.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
