apiVersion: v1
kind: Namespace
metadata:
  name: todo-app
  labels:
    name: todo-app
    app: todo-management
    phase: phase-5
---
apiVersion: v1
kind: Namespace
metadata:
  name: kafka
  labels:
    name: kafka
    app: kafka-cluster
    phase: phase-5
