apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: todo-app
type: Opaque
stringData:
  connectionString: "postgresql://todouser:todopass123@postgres:5432/tododb"
  jwtSecret: "your-super-secret-jwt-key-change-in-production-min-32-chars"
  betterAuthSecret: "your-better-auth-secret-key-min-32-chars-production"
  openaiApiKey: "sk-YOUR-OPENAI-API-KEY-HERE"
