apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: todo-app
type: Opaque
stringData:
  connectionString: "postgresql://todouser:todopass123@postgres:5432/tododb"
  jwtSecret: "your-super-secret-jwt-key-change-in-production-min-32-chars"
  betterAuthSecret: "your-better-auth-secret-key-min-32-chars-production"
  openaiApiKey: "sk-YOUR-OPENAI-API-KEY-HERE"

# ⚠️ INSTRUCTIONS:
# 1. Copy this file to: secrets.yaml (in the same directory)
# 2. Replace "sk-YOUR-OPENAI-API-KEY-HERE" with your real OpenAI API key
# 3. DO NOT commit the secrets.yaml file (it's in .gitignore)
# 4. This template file (secrets-template.yaml) is safe to commit
