# [Task]: T-D-003
# [From]: specs/005-phase-v-cloud/phase5-cloud.specify.md ยง3.1,
#         specs/005-phase-v-cloud/phase5-cloud.plan.md ยง5.1.3,
#         specs/005-phase-v-cloud/phase5-cloud.tasks.md ยงD.3

apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: kubernetes-secrets
  namespace: todo-app
spec:
  type: secretstores.kubernetes
  version: v1
  metadata: []

scopes:
- backend-service
- recurring-task-service
- notification-service
